version: "3"
services:
  node:
    image: mhart/alpine-node:11
    working_dir: /app
    volumes:
      - ./package.json:/app/package.json:cached
      - ./node_modules:/app/node_modules:cached
      - ./scripts:/app/scripts:cached
      - ./lib:/app/lib:cached
      - ./public:/app/public:cached
      - ./files:/app/files:cached
    command: npm run start:serve
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/someaudio
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - mongo

  mongo:
    image: mvertes/alpine-mongo
    working_dir: /app
    volumes:
      - ./db/:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017
